
AWSTemplateFormatVersion : 2010-09-09
Description: Apache Guacamole Server
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m4.large
    Description: Enter t2.micro, m1.small, or m4.large. Default is t2.micro.
  InstanceSubnet:
    Type: String
    Default: subnet-2b976000
    Description: subnet id of instance
  InstanceKeyPairParameter:
    Type: String
    Default: TreaEBSLab
    Description: Name of the KeyPair you choose to use to ssh into the box    
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-f4cc1de2
      KeyName:
        Ref: InstanceKeyPairParameter
      InstanceType:
        Ref: InstanceTypeParameter
      SecurityGroupIds:
        - sg-58e1fc3d
      SubnetId:
        Ref: InstanceSubnet
      Tags:
        -
          Key: Name
          Value: Apache Guacamole Server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          apt-get update -y
          yes | sudo apt-get install -y guacamole-tomcat libguac-client-ssh0 libguac-client-rdp0
          sudo /etc/init.d/guacd start
          sudo /etc/init.d/tomcat8 restart
